import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import AuthProvider from "./components/AuthProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
        <AuthProvider>
          <body className="bg-white">
              <Nav />
              <div className="m-2">{children}</div>
          </body>
        </AuthProvider>
    </html>
  );
}
